{% set name = "qstylizer" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/blambright/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 95f7666929cc34efbbd9e0640a13f507b8ec35ec34a9604017cf96c24f7f9ea6

build:
  number: 0
  skip: true  # [s390x]
  #Building this as a new dependency for spyder , which we don’t support on linux-ppc64le or linux-s390x. Therefore we’re skipping those platforms for this build.
  skip: true  # [py<37]
requirements:
  host:
    - python
    - pip
    - pbr
    - setuptools
    - wheel
  run:
    - python
    - tinycss2 >=1.1.0,<2.0
    - inflection >0.3.0,<1.0

test:
  imports:
    - qstylizer
    - qstylizer.style
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/blambright/qstylizer
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Qt stylesheet generation utility for PyQt/PySide '
  description: |
    qstylizer is a python package designed to help with the construction of
    PyQt/PySide stylesheets.
  doc_url: https://qstylizer.readthedocs.io
  dev_url: https://github.com/blambright/qstylizer

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - steff456
